
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
